grafana:
  persistence:
    enabled: true
    type: pvc
    size: 10Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: do-block-storage
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      searchNamespace: ALL
  extraConfigmapMounts:
    - name: grafana-alerting-policies
      mountPath: /etc/grafana/provisioning/alerting/policies.yaml
      subPath: policies.yaml
      configMap: grafana-alerting-policies
      readOnly: true
  extraSecretMounts:
    - name: grafana-alerting-contact-points
      mountPath: /etc/grafana/provisioning/alerting/contactpoints.yaml
      subPath: contactpoints.yaml
      secretName: grafana-alerting-contact-points
      readOnly: true
